### ISSUE TITLE
Erro em PathLib

### ISSUE THREAD

**Issue by tutalucena** [aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ#13]
Boa tarde! Estou tentando utilizar esta aplicação porém quando executo o algoritimo python ele dá o seguinte erro:

----------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Tuta\PycharmProjects\pythonProject2\Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ-master\code\ETL_coletar_dados_e_gravar_BD.py", line 25, in <module>
    output_files = Path(getEnv('OUTPUT_FILES_PATH'))
  File "C:\Users\Tuta\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 958, in __new__
    self = cls._from_parts(args)
  File "C:\Users\Tuta\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 592, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\Tuta\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 576, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

---------------------------

Eu estou utilizando o mesmo código que você criou, seguindo a alteração sutíl de ajustar para meu ambiente e também de baixar o postgreSQL e criar a base de dados. Por favor, pode me ajudar?
![erro_1](https://user-images.githubusercontent.com/74742050/141349630-eafd470a-836d-4291-b7bf-b8ef54834ce3.PNG)
![erro_ao_debugar](https://user-images.githubusercontent.com/74742050/141349636-90f06b5b-0cfa-4ae4-b94b-4f8130ace7cd.PNG)

**Comment by IuseArchByTWay** [comment]
Lê direito o item 2 do README.md

**Comment by tutalucena** [comment]
> Lê direito o item 2 do README.md
Valeu pelo toque.
