### ISSUE TITLE
urllib.error.ContentTooShortError

### ISSUE THREAD

**Issue by Diglee147** [aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ#19]
418] bytes - 
Downloading: 2% [3457024 / 165184418] bytes - 
Downloading: 2% [3465216 / 165184418] bytes - 
Downloading: 2% [3473408 / 165184418] bytes - Traceback (most recent call last):
  File "C:\Users\CTF 1\Desktop\Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ-master\code\ETL_coletar_dados_e_gravar_BD.py", line 72, in <module>
    wget.download(url, out=output_files, bar=bar_progress)
  File "C:\Users\CTF 1\AppData\Local\Programs\Python\Python310\lib\site-packages\wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "C:\Users\CTF 1\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 280, in urlretrieve
    raise ContentTooShortError(
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 3473237 out of 165184418 bytes>

Alguém sabe resolver? Vi um cara na internet falando que é só adicionar uma função de reiniciar / retomar download, vou dar uma pesquisada, mas se alguém puder ajudar agradeço !

**Comment by Diglee147** [comment]
solução: fazer o download na mao.
