### ISSUE TITLE
Erro na etapa de Tratamento dos Dados (Empresa)

### ISSUE THREAD

**Issue by WelJrParreira** [aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ#27]
Olá pessoal, tudo bom? Primeiramente agradecer o desenvolvimento dessa rotina, meus parabéns!

Agora venho aqui buscar uma ajuda, nessa etapa abaixo na imagem está acontecendo este erro, porém não estou sabendo identificar o motivo.

![image](https://user-images.githubusercontent.com/124322009/216487712-b98670c3-cb5a-4876-9a40-3ecfa4212d89.png)

________________________________________________________________________

#######################
#######################

Trabalhando no arquivo: K3241.K03200Y0.D30114.EMPRECSV [...]
Traceback (most recent call last):
  File "c:\Users\weljp\OneDrive\Área de Trabalho\Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ-master\Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ-master\code\ETL_coletar_dados_e_gravar_BD.py", line 205,
 in <module>
    empresa = pd.read_csv(filepath_or_buffer=extracted_file_path,
  File "C:\Users\weljp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\weljp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\weljp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\weljp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\parsers\readers.py", line 611, in _read
    return parser.read(nrows)
  File "C:\Users\weljp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\parsers\readers.py", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "C:\Users\weljp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas\_libs\parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas\_libs\parsers.pyx", line 866, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 1965, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 131671: invalid continuation byte
PS C:\Users\weljp\OneDrive\Área de Trabalho\VSCODEw>

________________________________________________________________________

Se puderem auxiliar, por gentileza.

**Comment by italojohnny** [comment]
O pr #28 resolve o problema.

**Comment by aphonsoar** [comment]
@WelJrParreira, consegue verificar se adicionando as alteracoes do [commit](https://github.com/aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ/pull/28/commits/637473c4908bc3de561d95add421bdf8bcd6d6d9) isso resolve seu problema?

**Comment by Lorenzobattistela** [comment]
@aphonsoar tive o mesmo erro e o commit do @italojohnny resolveu o problema
