### ISSUE TITLE
Falhando ao realizar o download - Estabelecimentos

### ISSUE THREAD

**Issue by jardeldargas** [aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ#53]
Olá pessoal, tudo bem?

Observei que a versão atual da aplicação está falhando ao entrar no download do "Estabelecimento4.zip".

No console da IDE retornou o seguinte erro:

Downloading: 53% [188555264 / 354795724] bytes - Traceback (most recent call last):
  File "ETL_coletar_dados_e_gravar_BD.py", line 161, in <module>
    wget.download(url, out=output_files, bar=bar_progress)
  File "C:\...\Python\Python38\lib\site-packages\wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "C:\...\Python\Python38\lib\urllib\request.py", line 276, in urlretrieve
    block = fp.read(bs)
  File "C:\...\Python\Python38\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "C:\...\Python\Python38\lib\http\client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "C:\...\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host.

Considerando a causa deste erro, será que poderia estar ocorrendo alguma limitação de rede na origem destes dados? Ou então alguém já identificou o mesmo em outro momento mas encontrou alguma solução?

Agradeço bastante.

**Comment by jardeldargas** [comment]
Srs, após a Receita liberar novos dados (no dia 05/07/24), o sistema seguiu todo o processo normalmente. De qualquer forma agradeço bastante!
